### ISSUE TITLE
Unable to import after pip install

### ISSUE THREAD

**Issue by GeoffSCollins** [IsaacLuo/SnapGeneFileReader#3]
Pip installed previously. Verified pip install with the command "pip install snapgene_reader" which gave the following results:

Requirement already satisfied: snapgene_reader in c:\python35\lib\site-packages (0.1.15)
Requirement already satisfied: biopython in c:\python35\lib\site-packages (from snapgene_reader) (1.73)
Requirement already satisfied: xmltodict in c:\python35\lib\site-packages (from snapgene_reader) (0.12.0)
Requirement already satisfied: html2text in c:\python35\lib\site-packages (from snapgene_reader) (2018.1.9)
Requirement already satisfied: numpy in c:\python35\lib\site-packages (from biopython->snapgene_reader) (1.13.1+mkl)

Python 3.7.0 interpreter is not finding snapgene_file_reader, xmltodict, or html2text as shown below:

>>> from snapgene_reader import snapgene_file_to_dict
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    from snapgene_reader import snapgene_file_to_dict
ModuleNotFoundError: No module named 'snapgene_reader'

>>> import xmltodict
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    import xmltodict
ModuleNotFoundError: No module named 'xmltodict'

>>> import html2text
Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    import html2text
ModuleNotFoundError: No module named 'html2text'

Perhaps pip is intalling in the wrong place? Other modules work fine on this windows 10 machine, only snapgene_reader and its dependencies that were installed (xmltodict and html2text). Previously had biopython and numpy. Any help is appreciated.

**Comment by GeoffSCollins** [comment]
Found the problem. For some reason, python was installed in C:/Python35 and C:/Users/Geoff/AppData/Local/Program/Python/Python37-32. I copied the folders for snapgene_reader and its dependencies from the AppData directory to the one in C:/Python35 and idle and other IDE's recognized the modules.
